export const LOAD_RANDOM_CAT_IMAGE = 'LOAD_RANDOM_CAT_IMAGE';
export const LOAD_RANDOM_CAT_IMAGE_START = `${LOAD_RANDOM_CAT_IMAGE}_START`;
export const LOAD_RANDOM_CAT_IMAGE_PROGRESS = `${LOAD_RANDOM_CAT_IMAGE}_PROGRESS`;
export const LOAD_RANDOM_CAT_IMAGE_SUCCESS = `${LOAD_RANDOM_CAT_IMAGE}_SUCCESS`;
export const LOAD_RANDOM_CAT_IMAGE_FAILED = `${LOAD_RANDOM_CAT_IMAGE}_FAILED`;
